package com.dmcsol.xdm.model.am;

import com.dmcsol.xdm.common.framework.ApplicationModuleImpl;
import com.dmcsol.xdm.common.framework.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 15 17:05:06 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestXdmCommonModelImpl extends com.dmcsol.xdm.common.framework.ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TestXdmCommonModelImpl() {
    }

    /**
     * Container's getter for ElementsView.
     * @return ElementsView
     */
    public com.dmcsol.xdm.common.framework.ViewObjectImpl getElementsView() {
        return (com.dmcsol.xdm.common.framework.ViewObjectImpl) findViewObject("ElementsView");
    }

    /**
     * Container's getter for EventsView.
     * @return EventsView
     */
    public com.dmcsol.xdm.common.framework.ViewObjectImpl getEventsView() {
        return (com.dmcsol.xdm.common.framework.ViewObjectImpl) findViewObject("EventsView");
    }

    /**
     * Container's getter for PersonsView.
     * @return PersonsView
     */
    public com.dmcsol.xdm.common.framework.ViewObjectImpl getPersonsView() {
        return (com.dmcsol.xdm.common.framework.ViewObjectImpl) findViewObject("PersonsView");
    }

    /**
     * Container's getter for ProgrammesView.
     * @return ProgrammesView
     */
    public com.dmcsol.xdm.common.framework.ViewObjectImpl getProgrammesView() {
        return (com.dmcsol.xdm.common.framework.ViewObjectImpl) findViewObject("ProgrammesView");
    }

    /**
     * Container's getter for TasksView.
     * @return TasksView
     */
    public com.dmcsol.xdm.common.framework.ViewObjectImpl getTasksView() {
        return (com.dmcsol.xdm.common.framework.ViewObjectImpl) findViewObject("TasksView");
    }
}

